on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 12
          run_install: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"

      - run: |
          pnpm i --frozen-lockfile
          pnpm build

      - uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4.1.5
        id: publish

      - name: Create Tag
        if: ${{ steps.publish.outputs.type }}
        id: create_tag
        uses: jaywcjlove/create-tag-action@4b8582e914640edc3602f7d9907f3821bf84bdc7 # v2.3.0
        with:
          package-path: ./package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@00eecde44f40feee4b5c96fe16e5cfdeab76336a # v2.4.0
        if: steps.create_tag.outputs.successful
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (Uninen|renovate-bot)
          show-emoji: false

      - name: Get the changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"

      - name: Create Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.changelog }}

            Compare changes: ${{ steps.changelog.outputs.compareurl }}

            Read more from the Changelog: https://github.com/slipmatio/toolbelt/blob/main/CHANGES.md
